---
# File: tasks/install_packages_RedHat.yml - OS packages for Red Hat

- name: Install EPEL repo.
  become: True
  become_user: root
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: ansible_pkg_mgr == 'yum'
  tags: ansible-hubot

- name: Import EPEL GPG key
  become: True
  become_user: root
  rpm_key:
    key: "{{ epel_repo_gpg_key }}"
    state: present
  tags: ansible-hubot

- name: install Development tools package group
  become: True
  become_user: root
  yum: name="@Development tools" state=present
  when: ansible_pkg_mgr == 'yum'
  changed_when: False
  tags: ansible-hubot

- name: Install RedHat packages
  become: True
  become_user: root
  yum: name={{ item }} state=present
  when: ansible_pkg_mgr == 'yum'
  with_items:
    - curl
    - git
    - libicu-devel
    - libselinux-python
    - openssl-devel
    - expat-devel
    - redis
  tags: ansible-hubot

- set_fact:
    redis_server: redis
  tags: ansible-hubot
