---
# Jenkins doesn't allow updates via CLI, though that is required before plugins
# can be installed via CLI. See: https://gist.github.com/rowan-m/1026918
- name: Create Jenkins updates folder.
  file:
    path: "{{ jenkins_home }}/updates"
    owner: "{{jenkins_user}}"
    group: "{{jenkins_group}}"
    mode: 0755
    state: directory
  register: jenkins_plugins_folder_create
  tags:
    - jenkins
- name: Update Jenkins plugin data.
  shell: curl -L https://updates.jenkins-ci.org/update-center.json | sed '1d;$d' > "{{ jenkins_home }}/updates/default.json"
  args:
    creates: "{{ jenkins_home }}/updates/default.json"
  tags:
    - jenkins
- name: Permissions for default.json updates info.
  file:
    path: "{{ jenkins_home }}/updates/default.json"
    owner: "{{jenkins_user}}"
    group: "{{jenkins_group}}"
    mode: 0755
  when: jenkins_plugins_folder_create.changed
  tags:
    - jenkins
- name: Check if we're using a password file for authentication
  stat:
    path: "{{ jenkins_admin_password_file }}"
  register: adminpasswordfile
  tags:
    - jenkins
# - name: Install Jenkins plugins using password.
#   command: >
#     {{JAVA_HOME}}/bin/java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix | default('') }}/
#     install-plugin {{ item }}
#     --username {{ jenkins_admin_username }}
#     --password {{ jenkins_admin_password }}
#     # creates="{{ jenkins_home }}/plugins/{{ item }}.jpi"
#   with_items: "{{ jenkins_plugins }}"
#   when: jenkins_admin_password != ""
#   notify: restart jenkins
#   ignore_errors: true
#   tags:
#     - jenkins

- name: Install Jenkins plugins using password.
  jenkins_plugin:
    name: "{{ item }}"
    jenkins_home: "{{ jenkins_home }}"
    params:
      url_username: "{{ jenkins_admin_username }}"
      url_password: "{{ jenkins_admin_password }}"
    timeout: "{{ jenkins_plugin_timeout }}"
    updates_expiration: "{{ jenkins_plugin_updates_expiration }}"
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix | default('') }}/"
    state: present
    validate_certs: False
  with_items: "{{ jenkins_plugins }}"
  when: jenkins_admin_password != ""
  ignore_errors: true
  notify: restart jenkins
